# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(355, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(90, 90))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("resources/image/unnamed.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.check_bur = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_bur.setFont(font)
        self.check_bur.setObjectName("check_bur")
        self.horizontalLayout_6.addWidget(self.check_bur)
        self.spin_bur = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_bur.sizePolicy().hasHeightForWidth())
        self.spin_bur.setSizePolicy(sizePolicy)
        self.spin_bur.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spin_bur.setObjectName("spin_bur")
        self.horizontalLayout_6.addWidget(self.spin_bur)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(90, 90))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/image/icecream.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.check_ice = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_ice.setFont(font)
        self.check_ice.setObjectName("check_ice")
        self.horizontalLayout_4.addWidget(self.check_ice)
        self.spin_ice = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_ice.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spin_ice.setObjectName("spin_ice")
        self.horizontalLayout_4.addWidget(self.spin_ice)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(90, 90))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("resources/image/unnamed.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.check_five = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_five.setFont(font)
        self.check_five.setObjectName("check_five")
        self.horizontalLayout_5.addWidget(self.check_five)
        self.spin_five = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_five.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spin_five.setObjectName("spin_five")
        self.horizontalLayout_5.addWidget(self.spin_five)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(90, 90))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("resources/image/24930_1.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.check_kur = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_kur.setFont(font)
        self.check_kur.setObjectName("check_kur")
        self.horizontalLayout_9.addWidget(self.check_kur)
        self.spin_kur = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_kur.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spin_kur.setObjectName("spin_kur")
        self.horizontalLayout_9.addWidget(self.spin_kur)
        self.gridLayout.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(150, 60))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("resources/image/42-429338_vector-kfc-logo-png-transparent-png.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setStyleSheet("background-color: rgba(255, 0, 0, 0.2);")
        self.textBrowser.setOverwriteMode(False)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 355, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_reset = QtWidgets.QAction(MainWindow)
        self.action_reset.setObjectName("action_reset")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menu.addSeparator()
        self.menu.addAction(self.action_reset)
        self.menu.addAction(self.action_exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KFC заказ"))
        self.check_bur.setText(_translate("MainWindow", "Чизбургер(80р)"))
        self.check_ice.setText(_translate("MainWindow", "Мороженное (69р)"))
        self.check_five.setText(_translate("MainWindow", "Ланчбокс (200р)"))
        self.pushButton.setText(_translate("MainWindow", "ПОДТВЕРДИТЬ ЗАКАЗ"))
        self.check_kur.setText(_translate("MainWindow", "Крылышки(450р)"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600;\">АКЦИЯ!!!!!  </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt;\">КУПИ 2 БУРГЕРА И ПОЛУЧИ КОЛУ</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:6pt; font-weight:600;\">!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Выберите из перечисленного:</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "Я передумал"))
        self.action_reset.setText(_translate("MainWindow", "Начать заново"))
        self.action_exit.setText(_translate("MainWindow", "Выход"))
